### ISSUE TITLE
Using paths for PR body

### ISSUE THREAD

**Issue by ricardomarsanc** [peter-evans/create-pull-request#1192] opened 2022-06-02 10:54 UTC
### Subject of the issue
I would like to define the PR body using a path to a file in the repository. I don't know if now it's possible, but if not, I think could be very useful for when creating PRs for new releases to be able to include the Changelog as the PR body

**Comment by fingolfin** [comment] 2022-06-02 13:17
After some searching, I believe this is a duplicate of this closed issue: https://github.com/peter-evans/create-pull-request/issues/1098

Perhaps to avoid such questions in the future, a brief section could be added to the README to point to those instructions?

**Comment by fingolfin** [comment] 2022-06-02 13:18
Hehe, OK, sorry for being dumb: It *is* documented at https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#setting-the-pull-request-body-from-a-file -- I just somehow did not find that page earlier. Apologies!

**Closed** 2022-06-02 13:25 UTC
