### ISSUE TITLE
PRs fail to create due to Error: For same-org, cross-repo pulls, 'head_repo' is required: {"resource":"PullRequest","field":"head","code":"invalid"}

### ISSUE THREAD

**Issue by davereid-pfg** [peter-evans/create-pull-request#1459] opened 2023-01-04 22:57 UTC
### Subject of the issue

I have a workflow that is pushing the branch but failing to create the pull request due to a new error, when the action has worked before:

```yaml
      - name: Generate token using the Github App
        uses: tibdex/github-app-token@v1
        if: ${{ env.UPDATER_APP_ID && env.UPDATER_PRIVATE_KEY }}
        id: app-token
        with:
          app_id: ${{ env.UPDATER_APP_ID }}
          private_key: ${{ env.UPDATER_PRIVATE_KEY }}
      - name: Create pull request containing any changed files
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: scheduled-updater-changes
          base: ${{ github.base_ref || github.ref_name }}
          delete-branch: true
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
          title: Automatic dependency updates
          body: Rest of the body truncated, not important.
```

### Steps to reproduce

Logs where the workflow fails:
```
Run peter-evans/create-pull-request@v3
  with:
    branch: scheduled-updater-changes
    base: main
    delete-branch: true
    token: ***
    title: Automatic dependency updates
    body: Rest of the body truncated, not important.
    add-paths: -A
  
    commit-message: [create-pull-request] automated change
    committer: GitHub <noreply@github.com>
    author: Reid-Dave_pfghub <Reid-Dave_pfghub@users.noreply.github.com>
    signoff: false
    draft: false
...
Pushing pull request branch to 'origin/scheduled-updater-changes'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/scheduled-updater-changes
  remote: 
  remote: Create a pull request for 'scheduled-updater-changes' on GitHub by visiting:        
  remote:      https://github.com/***/private-repo/pull/new/scheduled-updater-changes        
  remote: 
  To https://github.com/***/private-repo
   * [new branch]      HEAD -> scheduled-updater-changes
Create or update the pull request
  Attempting creation of pull request
  Error: For same-org, cross-repo pulls, 'head_repo' is required: {"resource":"PullRequest","field":"head","code":"invalid"}
```

I cannot link to the actual logs since it is a private repository.

The same exact workflow from Dec 22 succeeded:

```
Run peter-evans/create-pull-request@v3
  with:
    branch: scheduled-updater-changes
    base: main
    delete-branch: true
    token: ***
    title: Automatic dependency updates
    body: Rest of the body truncated, not important.
    add-paths: -A
  
    commit-message: [create-pull-request] automated change
    committer: GitHub <noreply@github.com>
    author: Reid-Dave_pfghub <Reid-Dave_pfghub@users.noreply.github.com>
    signoff: false
    draft: false
...
Pushing pull request branch to 'origin/scheduled-updater-changes'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/scheduled-updater-changes
  remote: 
  remote: Create a pull request for 'scheduled-updater-changes' on GitHub by visiting:        
  remote:      https://github.com/***/private-repo/pull/new/scheduled-updater-changes        
  remote: 
  To https://github.com/***/private-repo
   * [new branch]      HEAD -> scheduled-updater-changes
Create or update the pull request
  Attempting creation of pull request
  Created pull request #12 (***:scheduled-updater-changes => main)
```

I'm also not able to replicate this consistently. The same exact workflow works fine in another private repository, it seems to be this specific repository causing the issue.

**Comment by yktakaha4** [comment] 2023-01-05 00:39
I just encountered the same error.
It occurred in the organization's private repository, so it could be a factor.

**Comment by chachasikes** [comment] 2023-01-05 01:21
Following 

Similar issue - started 6-7 hours ago from the time of writing this message.
We got this error:

```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by chachasikes** [comment] 2023-01-05 01:22
Didn't see any issues with GitHub Actions for today
https://www.githubstatus.com/

**Comment by peter-evans** [comment] 2023-01-05 01:25
Thanks for the report. I'm looking into this.

There haven't been any changes to the action that I think could have caused this, so it's likely to be a change with GitHub's API.

@chachasikes The deprecation warning is unrelated. See https://github.com/peter-evans/create-pull-request/issues/1336

**Comment by peter-evans** [comment] 2023-01-05 01:33
@davereid-pfg I see that you are using `v3` of this action. Please could you upgrade to `v4` and check if that solves the issue. There were some changes that I made between those two versions that could be related.

**Comment by jbum** [comment] 2023-01-05 02:02
Can confirm it's happening with v4 (I'm working with @chachasikes )

**Comment by quantumfusion** [comment] 2023-01-05 02:03
I can confirm the problem is still there with `v4`. Also running in a private repo, I have consistently had the `'head_repo' is required` error.
Relevant snippets from the run on the private repo:
From setup, confirms using latest published version of the action
```
Wed, 04 Jan 2023 23:58:40 GMT Download action repository 'peter-evans/create-pull-request@v4' (SHA:2b011faafdcbc9ceb11414d64d0573f37c774b04)
```
And the same error as mentioned in OP:
```
Thu, 05 Jan 2023 00:12:39 GMT
Create or update the pull request
Thu, 05 Jan 2023 00:12:39 GMT   Attempting creation of pull request
Thu, 05 Jan 2023 00:12:40 GMT   Error: For same-org, cross-repo pulls, 'head_repo' is required: {"resource":"PullRequest","field":"head","code":"invalid"}
```
The theory around it being an API seems plausible, our last working run was at `Wed, 04 Jan 2023 21:30:52 GMT`.

**Comment by peter-evans** [comment] 2023-01-05 02:14
I've created a GitHub support ticket because I'm fairly sure this is a change to the API they have made. I don't know if it's intentional, but if it is the documentation is incorrect and there was no warning.

**Comment by peter-evans** [comment] 2023-01-05 02:38
I'm unable to reproduce this issue. Please could you explain a bit more about your scenario.

1. Are you creating a pull request remotely? (In a repo other than where the workflow is running)
2. Is the repo where the workflow runs private?
3. Is the remote repo private?
4. What type of token are you using? What scopes?
5. Are the repos in an org or user account?

**Comment by peter-evans** [comment] 2023-01-05 03:11
@jbum Thank you. So it looks like the repo for the workflow and where you are creating the pull request is the same. I wonder if the error is being caused because the workflow is triggered by `repository_dispatch` from a different repository. I noticed that your workflow also can be triggered manually by `workflow_dispatch`. Please could try manually running the workflow from the GitHub UI. If that works, then it could be a permissions change they have made to the `GITHUB_TOKEN` regarding being triggered from a different repo.

**Comment by jbum** [comment] 2023-01-05 03:13
Fwiw, I notice that the call right after "Attempting creation of pull request" is to octokit (which was updated some 7 hours ago, around the time the failures started for us?).  We will try that thanks!

**Comment by jbum** [comment] 2023-01-05 03:17
The manual run also fails (tried it in a different public repo we've been testing on). https://github.com/cagov/odi-publishing-11ty-sandbox/actions/runs/3843544700

**Comment by peter-evans** [comment] 2023-01-05 03:17
> Fwiw, I notice that the call right after "Attempting creation of pull request" is to octokit (which was updated some 7 hours ago, around the time the failures started for us?). We will try that thanks!

Octokit is a library in use by the action. But you are using `v4` of the action, the release of which hasn't changed since 28th November last year.
https://github.com/peter-evans/create-pull-request/releases/tag/v4

**Comment by jbum** [comment] 2023-01-05 03:18
Yes, understood. Don't think this is your issue.

**Comment by peter-evans** [comment] 2023-01-05 03:25
All my tests are passing, so I think this is a very specific issue. I'm trying to figure out the exact scenario.

Test run from a hour or so ago:
https://github.com/peter-evans/create-pull-request-tests/actions/runs/3843283956

**Comment by peter-evans** [comment] 2023-01-05 03:28
I forked your test repo, made a few changes to ignore secrets I don't have, and it seems to work.
https://github.com/peter-evans/odi-publishing-11ty-sandbox/actions/runs/3843584226/jobs/6545964628

**Comment by jbum** [comment] 2023-01-05 03:33
Woah! Trying that.

**Comment by peter-evans** [comment] 2023-01-05 03:36
I also tried it in an org and that works, too. I don't have any idea what is going on. 🤔 
https://github.com/create-pull-request/odi-publishing-11ty-sandbox/actions/runs/3843637176

**Comment by jbum** [comment] 2023-01-05 03:41
I suspect our token has expired (still fails if I comment out committer). Will continue investigating that. Thank so much for helping us isolate it. You want way above and beyond. 

It *is* curious that a few folks experienced this today...

**Comment by peter-evans** [comment] 2023-01-05 03:48
> I suspect our token has expired

It looks like you are using the default `GITHUB_TOKEN` for the repository. That token doesn't expire.
Or have you created a secret in your repository with the exact same name as the default token?

> It is curious that a few folks experienced this specific error message today...
That's why I would be surprised if this was just down to token expiration. Please let me know if you solve it.

**Comment by davereid-pfg** [comment] 2023-01-05 04:14
> Are you creating a pull request remotely? (In a repo other than where the workflow is running)
 
No, it is the same repository.

> Is the repo where the workflow runs private?

Yes

> Is the remote repo private?
Yes, but also same repository, not remote

> What type of token are you using? What scopes?
Generated via Github App using https://github.com/tibdex/github-app-token action.

```yml
    permissions:
      contents: write
      pull-requests: write
```

> Are the repos in an org or user account?

An organization account.

**Comment by davereid-pfg** [comment] 2023-01-05 04:15
The mysterious thing is that several other similar private repositories under the same organization account also didn't fail and were just fine, using the exact same workflow (and Github token generated via Github App). It is isolated to one repository itself.

**Comment by chachasikes** [comment] 2023-01-05 04:41
👋🏼 @davereid-pfg  
Interesting & mysterious indeed.

We are trying different configurations of setting head_repo - but no luck yet.

**Comment by jbum** [comment] 2023-01-05 04:42
We're pretty sure it's not the token or committer at this point...

**Comment by chachasikes** [comment] 2023-01-05 04:44
Not setting head_repo in create-pull-request. It may be a bug coming from octokit.
We are stopping for the night. Will revisit tomorrow.

**Comment by davereid-pfg** [comment] 2023-01-05 04:59
I just checked out the branch that was created in our workflow via this action locally for the repository and used `gh pr create --base main --title "Test" --body "Body"` which succeeded so it doesn't seem to me to be an issue with the API or cli at this point.

**Comment by Becram** [comment] 2023-01-05 06:18
@peter-evans I am having similar issue, my scenario it different than yours test case, I checkout a different repo and  use the actions to create pr into that repo. This might help reproduce the issue

**Comment by AxoniusTK** [comment] 2023-01-05 08:32
Hey everyone, same issue for me.
I'm using it for fork sync and since today (it runs every day) it's started doing that error
`For same-org, cross-repo pulls, 'head_repo' is required: {"resource":"PullRequest","field":"head","code":"invalid"}`

**Comment by akbast** [comment] 2023-01-05 09:25
I am having also the same issue and the same scenario which @davereid-pfg has described. I am using a reusable workflow in all of the private repositories in which this action used and it is configured with a GitHub App. In some of the repositories it suddenly stopped working.

**Comment by unkali** [comment] 2023-01-05 09:37
I saw the exact same error pop up yesterday during our workflow

**Comment by matanshk** [comment] 2023-01-05 10:04
Same issue appears in our public repo under our organization 

`For same-org, cross-repo pulls, 'head_repo' is required: {"resource":"PullRequest","field":"head","code":"invalid"}`

**Comment by peter-evans** [comment] 2023-01-05 10:22
I found this other issue by searching GitHub. It looks related.
https://github.com/coilhq/web-monetization-projects/issues/3558

I'm keeping an eye out for similar issues:
https://github.com/search?q=%22For+same-org%2C+cross-repo+pulls%22&type=issues

I haven't had a response from GitHub Support yet.

**Comment by gm3dmo** [comment] 2023-01-05 10:58
GitHub engineering are now investigating.

**Comment by akbast** [comment] 2023-01-05 11:11
I have tried in one of the failing repositories. It is working again.

**Comment by Becram** [comment] 2023-01-05 11:11
its working thank you

**Comment by gm3dmo** [comment] 2023-01-05 11:11
Apologies for the inconvenience.

**Comment by peter-evans** [comment] 2023-01-05 11:12
@gm3dmo Thank you for the fix!

**Comment by AxoniusTK** [comment] 2023-01-05 11:34
It was solved, thanks!

**Comment by clxmstaab** [comment] 2023-01-05 12:55
solved, thanks

**Comment by davereid-pfg** [comment] 2023-01-05 15:11
Can confirm as well, resolved today without any changes.

**Comment by jbum** [comment] 2023-01-05 15:16
@chachasikes and I can confirm as well. Working.

**Comment by jbum** [comment] 2023-01-05 15:32
Thank you everyone who reported this, and @peter-evans for investigating and @gm3dmo for the fix!

**Comment by peter-evans** [comment] 2023-01-06 01:01
Closing as resolved. Thank you everyone!

**Closed by peter-evans** 2023-01-06 01:01 UTC

**Comment by krebemm** [comment] 2023-08-23 20:46
getting same error Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}

it has been working all day too...

**Comment by krebemm** [comment] 2023-08-23 22:09
> getting same error Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}
> 
> it has been working all day too...

it is happening in two of my repos that have been using it for months and just today has ran 4 hrs ago as well. in my third testing repo, it is working as well

**Comment by krebemm** [comment] 2023-08-29 19:01
following up @peter-evans this is still happening unfortunately, do you have any suggestions?

**Comment by HarryZ10** [comment] 2024-02-14 18:21
@krebemm  did you get it working?

**Comment by krebemm** [comment] 2024-02-14 18:24
@HarryZ10 yes but i ended up just using git cli instead of this action, it has been reliable so far.
