### ISSUE TITLE
Action fails

### ISSUE THREAD

**Issue by gr2m** [peter-evans/create-pull-request#36] opened 2019-09-19 19:18 UTC
I've setup to use your action in a workflow of mine but it failed. Any idea what the problem could be? I'm not a Python developer so I'm not sure what went wrong exactly.

This is the error I got

> Traceback (most recent call last):
>   File "/create-pull-request.py", line 126, in <module>
>     if not ignore_event(github_event):
>   File "/create-pull-request.py", line 26, in ignore_event
>     deleted = "{deleted}".format(**github_event)
> KeyError: 'deleted'

https://github.com/octokit/rest.js/commit/1803cdcc0c6ee202528c00595338e72fb624c259/checks#step:8:16

**Comment by peter-evans** [comment] 2019-09-19 23:16
@gr2m I'm fairly sure the problem is that when using `on: repository_dispatch` the event data does not contain the `deleted` key that the code is checking. There was a similar issue previously when using `on: schedule` here https://github.com/peter-evans/create-pull-request/issues/29.

I have a feeling that the `deleted` key check is not even necessary anymore in Actions v2. I will test again and make a fix asap.

**Comment by peter-evans** [comment] 2019-09-20 00:48
This should now be fixed in the latest version of the action.
Please try `peter-evans/create-pull-request@v1.1.4`

**Comment by peter-evans** [comment] 2019-09-20 01:26
Latest version is now `peter-evans/create-pull-request@v1.2.0`.

Closing this issue. Please reopen if you experience further problems.

**Closed by peter-evans** 2019-09-20 01:26 UTC
