### ISSUE TITLE
diff with existing branch not detected

### ISSUE THREAD

**Issue by matfax** [peter-evans/create-pull-request#82] opened 2019-12-04 17:52 UTC
Hi Peter,

I'm facing the issue that changes after the initial commit are not recognized as such.

My use case is a reformatting of the codebase and pushing it into a PR.
If the codebase changes and the PR has not yet been merged, an update of the existing PR seems to be appropriate, so I'm using the `branch-suffix: none` option here.
However, new changes from the master branch are not correctly detected. My guess is that the checkout of the master branch makes the local branch "undirty" by discarding changes on the rebase or merge. The two branches are definitely different but not detected. As a result, the existing PR is shown with conflicts.

An alternative option would be a force push. The commits themselves only include changes. If other files are affected so that there would be no conflict, the commits won't change, are thus equal and do not need to be pushed. A force push has the advantage that there is only one commit to compare against. Either that commit is different or it is not.

Here my log:

```
Currently checked out base assumed to be branch 'master'
Pull request branch to create/update set to 'black'
Pull request branch 'black' already exists as remote branch 'origin/black'
Checking out branch 'black'
Checking for local working copy changes indicating a diff with existing pull request branch 'origin/black' # local black and origin/black are different
No modified or untracked files detected. Skipping.
```

Here is the [PR](https://github.com/matfax/mutapath/pull/34) and the [action](https://github.com/matfax/mutapath/commit/05b03d47d539dad810107bd27dad744ab2d6716c/checks?check_suite_id=341864576).

**Comment by peter-evans** [comment] 2019-12-05 04:56
@matfax Thank you for creating a new issue to discuss this. I think my first impression about this was wrong and I believe the problem is simpler. 

> new changes from the master branch are not correctly detected

The action does not rebase the PR branch. It used to rebase, [but I removed it](https://github.com/peter-evans/create-pull-request/issues/50#issuecomment-537437166).

So what happens is that local changes that apply to new commits on `master` are lost when branch `black` is checked out and the stash popped. You can try to see if it works correctly by manually rebasing the PR branch and running the workflow again. The diff should then be correct.

I will think about how to add rebase back in to the action safely.

I hope I've understood this correctly. Does that make sense to you, too?

**Comment by matfax** [comment] 2019-12-08 14:38
@peter-evans I'm not sure if rebasing would solve this issue. Rebasing per se would not work because there still were the conflicts, so I chose to merge with a `--strategy=ours`. That did not work either. Then, I had a more thorough look at the code and tried to reproduce the issue by manually performing the git commands.
The checkout causes the problem, in the first hand. The stash pop fails:
```
Auto-merging tests/helper.py
CONFLICT (content): Merge conflict in tests/helper.py
...
```
The subsequent checkout and reset confuse things for me. The [action](https://github.com/matfax/mutapath/commit/341e7f78e8a79db7e7290392a0ecf5b32c1431bb/checks?check_suite_id=347800851) does not seem to detect the branch to be dirty. However, my local version is dirty. I pushed my local version [now](https://github.com/matfax/mutapath/pull/34) and even though there are still two conflicts, they seem to be related to inconsistent formatting.

I wondered why you chose to checkout first and commit afterward, unlike in a manual use case scenario in that you would typically commit first and then try to push. If that fails, you would rebase or merge respectively so that the subsequent push would succeed. That seems to be more straight-forward and should most definitely solve issues like mine.

0. Set metadata
1. Commit
2. Push to the remote branch with the given name. If that branch is new, the push will succeed. If the branch already exists and has a conflict, it will fail.
3. If the push failed, use rebase or merge from the current remote of the local branch to solve the conflicts, respecting the user preference (i.e., action inputs) and the chosen the strategy (i.e., ours, theirs) as well.
4. Push again.

**Comment by peter-evans** [comment] 2019-12-09 02:04
The reason it tries to checkout first is to pop the stash on top of the PR branch. It seemed like a good approach at the time. I now realise there are better ways and I'm in the process of changing it for a `v2` major version release. 

You might be right that rebase alone wouldn't solve it. There may even be conflict cases where it would be impossible for the action to decide what to do and it would just need to fail and request manual intervention.

What would help me tremendously is being able to reproduce this scenario in a test case. Do you know the steps in simple git commands that can put the repository in the state you experienced? I'm trying to put together a set of test cases to make sure I cover conflict scenarios and edge cases for `v2`.

**Comment by matfax** [comment] 2019-12-15 15:55
@peter-evans Here is a simple test scenario but one that would be mergeable without a strategy.

**Setup repository:**
1.  `git init`
1. `echo "Test" > file1`
1. `git add file1`
1. `git commit -m "file1"`

**Create clone branch (representing local/master):**
1. `git branch clone`
1. `git checkout clone`
1. `echo "Addition" >> file1` (deterministic modification)
1. `git add file1`
1. `git commit -m "Addition1"` (representing the state of the new PR branch)

**Modify master:**
1. `git checkout master`
1. `echo "Test" > file2`
1. `git add file2`
1. `git commit -m "file2"`

**Create 2nd clone branch (representing local/master at a later time):**
1. `git branch later`
1. `git checkout later`
1. `echo "Addition" >> file1 && echo "Addition" >> file2` (deterministic modification)

**Branch is dirty now, but mergeable. Let's test what `create-pull-request` currently does:**
1. Check if the remote exists (assuming True)
1. `git stash --include-untracked`
1. `git checkout clone`
1. `git stash pop` (=> conflict in file2)
1. `git checkout --theirs .` (assuming BaseException is raised due to the conflict)
1. `git reset` (assuming BaseException is raised due to the conflict)
1. `git status` (commit and push if it is dirty)
1. file2 is untracked
This would still work because it would merge without conflicts. In my case, there are conflicts that require a merging strategy.

**Comment by matfax** [comment] 2019-12-15 16:08
Now, let's try a scenario that creates a dirty branch:

**Setup repository:**
1.  `git init`
1. `echo "Test" > file1`
1. `git add file1`
1. `git commit -m "file1"`

**Create clone branch (representing local/master):**
1. `git branch clone`
1. `git checkout clone`
1. `echo "Addition" >> file1` (deterministic modification)
1. `git add file1`
1. `git commit -m "Addition1"` (representing the state of the new PR branch)

**Modify master:**
1. `git checkout master`
1. `echo "Test2" >> file1`
1. `git add file1`
1. `git commit -m "modified file1"`

**Create 2nd clone branch (representing local/master at a later time):**
1. `git branch later`
1. `git checkout later`
1. `echo "Addition" >> file1 && echo "Addition" >> file2` (deterministic modification)

**Branch is dirty now, but mergeable. Let's test what `create-pull-request` currently does:**
1. Check if the remote exists (assuming True)
1. `git stash --include-untracked`
1. `git checkout clone`
1. `git stash pop` (=> conflict in file1)
1. `git checkout --theirs .` (assuming BaseException is raised due to the conflict)
1. `git reset` (assuming BaseException is raised due to the conflict)
1. `git status` (commit and push if it is dirty)
1. file1 is dirty, should be detected as such

**Comment by matfax** [comment] 2019-12-15 17:02
Finally, let's test a scenario that creates a branch that can not be merged without a strategy:

**Setup repository:**
1.  `git init`
1. `echo "Test" > file1`
1. `git add file1`
1. `git commit -m "file1"`

**Create clone branch (representing local/master):**
1. `git branch clone`
1. `git checkout clone`
1. `echo "Other" > file1` (simulating deterministic modification that replaces "Test" with "Other")
1. `git commit -a -m "replaced test with other"` (representing the state of the new PR branch)

**Modify master:**
1. `git checkout master`
1. `echo "Test2" >> file1`
1. `git commit -a -m "modified file1"`

**Create 2nd clone branch (representing local/master at a later time):**
1. `git branch later`
1. `git checkout later`
1. `echo "Later" > file1 && echo "Later2" >> file1` (simulating deterministic modification with a new version that replaces "Test" with "Later")

**Branch is dirty now and not mergeable. Let's test what `create-pull-request` currently does:**
1. Check if the remote exists (assuming True)
1. `git stash --include-untracked`
1. `git checkout clone`
1. `git stash pop` (=> conflict in file1)
1. `git checkout --theirs .` (assuming BaseException is raised due to the conflict)
1. `git reset` (assuming BaseException is raised due to the conflict)
1. `git status` (commit and push if it is dirty)
1. file1 is dirty, should be detected as such (bug? or is the BaseException not raised?)

**New try, this time with a previous merge as discussed earlier:**
1. `git merge clone` (fails because of conflict)
1. `git merge --strategy=ours clone` (succeeds)
1. Check if the remote exists (assuming True)
1. `git stash --include-untracked`
1. `git checkout clone`
1. `git stash pop` (=> conflict in file1)
1. `git checkout --theirs .` (assuming BaseException is raised due to the conflict)
1. `git reset` (assuming BaseException is raised due to the conflict)
1. `git status` (commit and push if it is dirty)
1. file1 is dirty, merge was useless

**New try, this time with a previous commit & merge:**
1. `git commit -a -m "replaced test with later"`
1. `git merge clone` (fails because of conflict)
1. `git merge --strategy-option=ours clone` (succeeds)
Even though only a push would be left to do:
1. Check if the remote exists (assuming True)
1. `git stash --include-untracked`
1. `git checkout clone`
1. `git stash pop` (=> no changes)
1. `git status` (nothing to commit, will not be pushed)

**Comment by matfax** [comment] 2019-12-15 17:08
After all, I could not reproduce a test state in which the branch was neither dirty nor had untracked-files. However, the branch is not detected to be dirty by the deployed version of `create-pull-request`. Preceding merging as a workaround does not change anything.

**Comment by peter-evans** [comment] 2019-12-17 04:07
@matfax Thank you for these scenarios. In the middle of working on `v2` at the moment so I'll work through these and try to make sure the next major version behaves sensibly.

**Comment by peter-evans** [comment] 2019-12-27 09:58
@matfax I've worked through many different test scenarios and completely refactored the way the action handles creating/updating pull request branches. It's still alpha right now, but feel free to test it out and let me know how it behaves. The big change is that each update will now factor in all new changes on the base. This is effectively a rebase of the pull request branch. This should solve your original problem that changes on master were not being reflected in updates to the PR.

A couple of breaking changes:
- `v2` of this action now requires repositories to be checked out with `actions/checkout@v2`.
- `branch-suffix: none` is now the default. So if you had that set, just remove it.
- `author-name`, `author-email`, `committer-name`, `committer-email` have been removed in favour of `author` and `committer`.
  They can both be set in the format `Display Name <email@address.com>`

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by peter-evans** [comment] 2020-01-03 06:38
`v2` has been released.

```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

@matfax I'm going to close this issue for now. Please reopen or create a new issue if you find that `v2` doesn't behave well for your use case.

**Closed by peter-evans** 2020-01-03 06:38 UTC
