### ISSUE TITLE
Authenticating with git extraheader causes error, possibly in combination with Git LFS

### ISSUE THREAD

**Issue by mimecuvalo** [peter-evans/create-pull-request#126] opened 2020-02-20 07:01 UTC
### Subject of the issue

The latest commit breaks for us https://github.com/peter-evans/create-pull-request/commit/289fda9fea034d9f05fb78954136955876e8e1b8

The stack trace is:
```
Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/src/create_pull_request.py", line 196, in <module>
    repo.git.push("--force", repo_url, f"HEAD:refs/heads/{branch}")
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git -c http.https://github.com/.extraheader=AUTHORIZATION: basic *** push --force <edited out> HEAD:refs/heads/create-pull-request/patch-1582181599
  stderr: 'batch response: Client error: <edited out>/info/lfs/objects/batch
error: failed to push some refs to '<edited out>''
```

### Steps to reproduce

My GitHub action involves a Git LFS file which may be an added factor, not sure.

**Comment by peter-evans** [comment] 2020-02-20 07:38
@mimecuvalo Thank you for raising this issue. This is interesting because https://github.com/peter-evans/create-pull-request/commit/289fda9fea034d9f05fb78954136955876e8e1b8 was an attempt to copy how the official `actions/checkout` action handles authentication.

I've found [Git LFS tests](https://github.com/git-lfs/git-lfs/blob/master/t/t-extra-header.sh) that strongly suggest it does work with `extraheader` so it looks fixable. I will try to reproduce this problem in a workflow.

It would be helpful if you could provide a more complete workflow to help me reproduce this.

**Comment by peter-evans** [comment] 2020-02-20 12:37
I've discovered that this is a possible bug with Git LFS itself.
Created this issue to report my findings: https://github.com/git-lfs/git-lfs/issues/4031

For now, please version pin to `v2.4.1`.
```
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mimecuvalo** [comment] 2020-02-20 16:06
Thanks for investigating! And thanks for the great package you've written - super useful ^_^

**Comment by peter-evans** [comment] 2020-02-22 06:11
@mimecuvalo This should now be fixed in the latest release.

My test case for this creates an LFS tracked file and it is successfully pushed to a branch.
```
      - name: Create LFS tracked file
        run: |
          git lfs track "*.dat"
          date +%s > large_file.dat
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mimecuvalo** [comment] 2020-02-22 16:19
Thanks for fixing it so fast! I was following the discussion on the other bug - was great to see the git-lfs team being so responsive, too :)

**Closed** 2020-02-22 16:19 UTC
