### ISSUE TITLE
Keeps on failing: fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by qdm12** [peter-evans/create-pull-request#142] opened 2020-03-27 00:13 UTC
I have the following Github workflow

```yml
name: Misspells
on: [pull_request,push]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
```

But unfortunately it fails with the logs when a pull request is made:

```
Target repository set to qdm12/pingodown
  stderr: 'fatal: ref HEAD is not a symbolic ref'
##[error]The checked out ref is not a valid base for a pull request. Unable to continue. Exiting.
##[error]The process '/opt/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1
/usr/bin/git config --local --add http.https://github.com/.extraheader AUTHORIZATION: basic ***
```

[Full log](https://github.com/qdm12/pingodown/runs/537816859?check_suite_focus=true)

[Example of PR from typo branch](https://github.com/qdm12/pingodown/pull/1)

Any help would be greatly appreciated as I would ideally like to use this action for other workflows as well! 👍

**Comment by peter-evans** [comment] 2020-03-27 01:00
Hi @qdm12 

The issue is that `pull_request` events checkout a merge commit. If you want to raise a pull request to merge into an existing pull request you need to checkout the `head_ref`. See the documentation here:
https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#pull-request-events

Also, `push` should only run on `master` so that you aren't creating two PRs for pull request branches.
```
name: Misspells
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on push
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Checkout on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
```

When using `branch-suffix: timestamp`, you might end up with a lot of PRs created if your repo has a lot of activity. It can be a bit awkward to use this action well on `pull_request` events. Personally, I would avoid if possible and just make the solution simpler by running on push to `master` only. That way you can use the fixed-branch strategy easier.

```
name: Misspells
on:
  push:
    branches:
      - master
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
```

**Comment by peter-evans** [comment] 2020-03-27 01:14
If you want to perform an operations on PRs (like correcting typos, formatting) I recommend using a slash command instead of raising another PR to merge into the PR branch. See [slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch), and in particular, the [ChatOps in Pull Requests demo](https://github.com/peter-evans/slash-command-dispatch/pull/8).

**Comment by qdm12** [comment] 2020-03-28 15:16
Thanks so much for the detailed help!

I'll stick with the PR approach for now (not too much activity yet / not too much spelling mistakes 😆 ), although your other slash command action is quite exciting as well.

Have a great weekend!!

**Comment by qdm12** [comment] 2020-03-28 22:21
Hi again,

Actually would you know the checkout step so that it would work for PR from forked repositories? In my case it's [this log](https://github.com/qdm12/cloudflare-dns-server/runs/542194302?check_suite_focus=true) I obtain, using [this workflow file](https://github.com/qdm12/cloudflare-dns-server/blob/master/.github/workflows/misspell.yml#L16) - almost the same as yours I think.

Thank you so much 👍

**Comment by peter-evans** [comment] 2020-03-29 00:49
Apparently, this will work for both local PRs and PRs from forks. I will update the docs to this snippet instead of the one I mentioned above.

```
- uses: actions/checkout@v2
  with:
    ref: ${{ github.event.pull_request.head.sha }}
```

**Comment by qdm12** [comment] 2020-03-29 18:47
Actually using this format gives the same error as before 😢  ([log](https://github.com/qdm12/private-internet-access-docker/pull/114/checks?check_run_id=543627325) and [workflow](https://github.com/qdm12/private-internet-access-docker/blob/windscribe/.github/workflows/misspell.yml))

**Comment by peter-evans** [comment] 2020-03-30 09:20
Sorry @qdm12. I didn't think about this long enough before I replied with [this comment](https://github.com/peter-evans/create-pull-request/issues/142#issuecomment-605539982). I've tried a lot of this in the past and essentially gave up. Basically, what you are trying to do is not possible with PRs from forks (or the workaround is so complicated it's undesirable). The PR branch lives in the fork. Most likely you have no access to the fork. So when you think about it, what is this workflow trying to do? You want to create a pull request in the fork to update the PR branch? The only way you could do that is if you have write access to the fork, or, you create a *fork of the fork* and raise a PR back to update it.

So one option would be to only run on `pull_request` events when the PR is local and not from a fork. This would still check when the fork PRs are merged to `master`.
```diff
name: Misspells
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  misspell:
+   # Check if the PR is not from a fork
+   if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on push
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Checkout on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
-         ref: ${{ github.event.pull_request.head.sha }}
+         ref: ${{ github.head_ref }}
      - name: reviewdog fixer
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Typos fixes'
          title: "Typos fixes"
          branch: typos
          branch-suffix: timestamp
```

As I mentioned previously, if you really want a solution to check/fix both local and fork PRs I suggest to use [slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch).

**Comment by peter-evans** [comment] 2020-04-13 00:43
@qdm12 Hope you managed to find a setup that works well for you. Closing this issue for now.

**Closed by peter-evans** 2020-04-13 00:43 UTC
