### ISSUE TITLE
Autosync PR out of date

### ISSUE THREAD

**Issue by paymog** [peter-evans/create-pull-request#3124] opened 2024-08-09 15:28 UTC
### Subject of the issue

I'm following the pattern for the auto-sync PR to keep my `prod` branch up to date with my `dev` branch. I just merged one of these PRs. then I pushed another commit to dev, the new PR was created, but I see that it's out of date

<img width="980" alt="image" src="https://github.com/user-attachments/assets/cba4d1a8-76b3-4f91-9788-fd5cd2a07320">

Here's my workflow

```
name: Auto PR from dev to prod

on:
  push:
    branches:
      - dev

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: prod-promotion
          delete-branch: true
          title: "Auto PR: Merge changes from dev to prod"
          body: "This pull request has been automatically created to merge changes from the dev branch into the prod branch."
```

**Comment by paymog** [comment] 2024-08-09 15:28
What's interesting, is that the single commit in the list is correct and as expected.

**Comment by peter-evans** [comment] 2024-08-12 08:21
Hi @paymog 

I'm not really sure. It might be possible to "reset" by recreating the `dev` branch on the HEAD of `prod` and trying again.

Or you could click to update the branch and see what gets merged in. It might give a clue to what the issue is.

**Closed** 2024-10-22 09:27 UTC
