### ISSUE TITLE
Error when using request-to-parent with fork whose HEAD is behind upstream

### ISSUE THREAD

**Issue by willsALMANJ** [peter-evans/create-pull-request#388] opened 2020-06-25 18:34 UTC
### Subject of the issue

I noticed that when I try to push to a fork and use request-to-parent with a fork whose HEAD is behind the parent's that I get an error if the CPR_BRANCH does not exist on the fork repo.

Here is my setup:

* An `upstream` repo that I want pull requests to go to
* A `fork` repo that is a fork of `upstream`. Pull requests to `upstream` should be made with branches from this repo.
* An `actions` repo that runs a GitHub action that calls create-pull-request with `upstream` and `fork`

The actual workflow is [here](https://github.com/willsALMANJ/flatpak_check_runtime/blob/1002c99c8408da176f3db8d3de7e370ca090cdb6/.github/workflows/main.yml#L1). I am using the method of checking out `upstream` and then running `git remote set-url origin ...` and `git fetch --unshallow -p origin` to point the remote at `fork` as suggested in the documentation for [pushing a pull request branch to a fork](https://github.com/peter-evans/create-pull-request/blob/926d56fcba4e2c2a3607430a2865fe20f888401c/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork).

I noticed that when HEAD of `upstream` gets updated ahead of `fork` and the CPR_BRANCH does not exist yet on `fork` that create-pull-request errors out with a log like this

```
Target repository set to willsALMANJ/de.klayout.KLayout
Pull request branch to create or update set to 'create-pull-request/patch'
Configured git committer as 'GitHub <noreply@github.com>'
Configured git author as 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
Pull request branch 'create-pull-request/patch' does not exist yet
Created branch 'create-pull-request/patch'
Pushing pull request branch to 'origin/create-pull-request/patch'
Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/172ec762f8ac8e050062398456fccd30444f8f30/dist/cpr/create_or_update_pull_request.py", line 88, in create_or_update_pull_request
    pull_request = github_repo.create_pull(
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/Repository.py", line 1348, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/Repository.py", line 1379, in __create_pull_1
    return self.__create_pull(
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/Repository.py", line 1392, in __create_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "code": "custom", "message": "No commits between flathub:master and willsALMANJ:create-pull-request/patch"}], "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/172ec762f8ac8e050062398456fccd30444f8f30/dist/cpr/create_pull_request.py", line 213, in <module>
    coupr.create_or_update_pull_request(
  File "/home/runner/work/_actions/peter-evans/create-pull-request/172ec762f8ac8e050062398456fccd30444f8f30/dist/cpr/create_or_update_pull_request.py", line 102, in create_or_update_pull_request
    pull_request = github_repo.get_pulls(
  File "/home/runner/work/_tool/Python/3.8.3/x64/lib/python3.8/site-packages/github/PaginatedList.py", line 51, in __getitem__
    return self.__elements[index]
IndexError: list index out of range
```

I looked into the code some to understand what was happening. What I found was that:

1. The local repo gets checked out matching `upstream` and the PR get based off of its HEAD, and in the case of no new changes points to its HEAD.
2. `repo.git.fetch("--force", repo_url, f"{working_base}:{working_base}")` in create_or_update_branch.py changes the local repo's base branch to match `fork`'s HEAD instead of `upstream`'s.
3. `diff = is_ahead(repo, base, branch)` is then true, even if the action generated no changes and `branch` is just pointing to `upstream` HEAD because that is ahead of `fork`'s HEAD.
4. create_or_update_pull_request.py tries to create a pull request but the PR branch matches `upstream`'s HEAD so it fails.
5. Then it tries to get the list of pull requests to update one that matches the current branch but fails because there are no such pull requests and it tries to access index 0 of the empty list.

I also found there is no error if the action is re-run. In this case, the PR branch already exists from the previous run and the current PR gets compared to this branch on the fork which will be even if there are no new changes between the two runs.

### Steps to reproduce

I don't think the separate `action` repo is necessary to reproduce the problem. So I think the steps to reproduce are:

1. Create an action that checks out an `upstream` repo.
2. Have that action redirect the checked out repo's origin to a fork with something like:
```
    - name: Point git remote to fork
      run: |
        git config user.password ${{ secrets.PAT }}
        git remote set-url origin https://github.com/${{ matrix.config.fork }}/${{ matrix.config.repo }}
        git fetch --unshallow -p origin
      working-directory: ${{ matrix.config.repo }}
```
3. Ensure that the `fork`'s HEAD is behind the `upstream`'s HEAD.
4. Have the action call create-pull-request with request-to-parent like:
```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@172ec762f8ac8e050062398456fccd30444f8f30
      with:
        path: ${{ matrix.config.repo }}
        title: Update runtime version
        token: ${{ secrets.PAT }}
        request-to-parent: true
```
5. Run the action so that it does not produce any changes to the repo.

Ideally, this case would produce no PR or error, but it errors out if the CPR_BRANCH does not exist already on the `fork`.

### Mitigation

I am not sure about the best way of avoiding this problem.

1. One work around would be to force push `upstream` HEAD to `fork` HEAD before calling create-pull-request to keep them in sync.
2. Maybe create-pull-request needs to handle the repo it is pushing to versus the repo it is opening the PR against more carefully? Perhaps instead of `request-to-parent` there could be `push-to-fork` that specified a fork to push to (and point to in the PR) and otherwise the local repo used in the action was left as a clone of the parent (without redirecting origin to point at the fork)?

**Comment by peter-evans** [comment] 2020-06-26 02:19
@willsALMANJ Thank you for such a detailed report of the issue! Your explanation makes sense and I understand the problem. I will need to take some time to reproduce it in a test and think about how to fix it.

**Comment by peter-evans** [comment] 2020-06-27 08:22
@willsALMANJ As you mentioned, one workaround is to force push to update the fork `base` for the PR. I've reworked the setup for preparing the fork and also made a small fix to support it that I've released as `v2.8.1`.

Please try the following. Note that you should set `persist-credentials: false` on checkout of the parent repository. We don't need these credentials after checkout and they override credentials in the remote URL in the next step causing an error.
```
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: |
          git remote set-url origin https://${{ secrets.MACHINE_USER_PAT }}:x-oauth-basic@github.com/machine-user/fork-of-repository
          git fetch --unshallow -p origin
          git push --force
```

Assuming there are no issues with this I will update the documentation to revise the setup steps for the `request-to-parent` feature.

I'm planning to redesign how this feature works in the next major version to remove the need for this setup. It will likely work similar to how you have imagined with something like a `push-to-fork` input.

**Comment by willsALMANJ** [comment] 2020-06-30 21:39
Thanks, I just tried out your suggested changes for force pushing to the fork and they worked for me.

**Comment by peter-evans** [comment] 2020-07-01 00:48
@willsALMANJ Great. Thanks for checking.

I've updated the docs to reflect this new way to setup the fork. https://github.com/peter-evans/create-pull-request/commit/40e70b8f7b4f2b5c96d75987c33edeb013cb81ab

cc: @jderusse because I know you use this feature.

I'll close this ticket for now, but as I mentioned, this is on my roadmap to redesign in `v3`.

**Closed by peter-evans** 2020-07-01 00:48 UTC

**Comment by jderusse** [comment] 2020-07-01 05:48
thank you for the ping. Indeed, we've ended to the sake conclusion.


https://github.com/async-aws/aws/blob/7649b3383ee8f53a2360b9faae87d98a200f07ee/.github/workflows/watch.yml#L27-L30

**Comment by peter-evans** [comment] 2020-07-01 07:10
Good to know you reached the same solution. Thanks!

**Comment by peter-evans** [comment] 2020-07-19 08:29
@willsALMANJ @jderusse I'm now testing `v3` of this action. I've redesigned `request-to-parent` in favour of a new input called `push-to-fork`. This removes the need for the preparation step beforehand and simplifies the feature greatly. If you have time, please test out the `v3-alpha` version of the action.

```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - uses: peter-evans/create-pull-request@v3-alpha
        with:
          token: ${{ secrets.MACHINE_USER_PAT }}
          push-to-fork: machine-user/fork-of-repository
```

Change notes for `v3` can be found in the `dev` branch here: https://github.com/peter-evans/create-pull-request/blob/dev/docs/updating.md

**Comment by jderusse** [comment] 2020-07-21 21:29
@peter-evans tested on our repo (https://github.com/async-aws/aws/pull/713) . It worked well.

Thanks

**Comment by peter-evans** [comment] 2020-07-21 23:43
@jderusse Great. Thank you for the feedback!

**Comment by peter-evans** [comment] 2020-07-23 09:02
Merged and released `v3`.
